console.clear()
console.log('Iniciando api-commonjs10')

const {suma, resta, multiplicacion, division, potencia, raiz} = require ('./funciones')
console.log(suma(2,2))
console.log(resta(6,3))
console.log(multiplicacion(5,2))
console.log(division(15,3))
console.log(potencia(8,2))
console.log(raiz(3,3))