console.clear()
console.log('Iniciando api-commonjs8')

const {suma, resta, multiplicacion, division, potencia, raiz} = require ('./funciones')
console.log(suma(7,2))
console.log(resta(15, 5))
console.log(multiplicacion(8,2))
console.log(division(6,2))
console.log(potencia(7,2))
console.log(raiz(6,2))