console.clear()
console.log('Iniciando api commonds2')

const {suma, resta, multiplicacion, division, potencia, raiz} = require ('./funciones')
console.log(suma(2,6))
console.log(resta(3,2))
console.log(multiplicacion(4,3))
console.log(division(15, 2))
console.log(potencia(2,5))
console.log(raiz(4,2))