console.clear()
console.log('Iniciando api-commondjs4')

const  { suma, resta, multiplicacion, division, potencia, raiz} = require('./funciones')
console.log(suma(2,7))
console.log(resta(3,3))
console.log(multiplicacion(2,2))
console.log(division(3,2))
console.log(potencia(2,2))
console.log(raiz(4,2))